# Generated by Django 3.2.10 on 2022-01-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommend_history',
            old_name='Recommend',
            new_name='recommend',
        ),
    ]
