# Generated by Django 3.2.10 on 2022-01-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0002_rename_recommend_recommend_history_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend_history',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recommend_history',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
